### ISSUE TITLE
What is BOT_URL?

### ISSUE THREAD

**Issue by Klavishnik** [jag-k/owntinfoil#51]
Hello!
I'm trying to run this project and I can't figure out what the parameter means BOT_URL.
I use a tg bot @Switch_library_bot, but url "https://t.me/Switch_library_bot" does not work.

**Comment by jag-k** [comment]
Hi! Sorry for too late. I added answer to your question in [FAQ on Wiki](https://github.com/jag-k/owntinfoil/wiki/FAQ#whats-the-bot_url)

> This is a special URL, which **Lord of the Bots** ask not to share in this repo. You can ask this in a [Telegram Group](https://t.me/NSW_TorrentLibrary) and ping a Chat Admin *or you can ask this in my DM :)*
